---
title: "datadict"
output: html_document
---

#Setting Up

```{r}
library(xgboost)
library(caret)
library(dplyr)
```

#Constant variables

```{r}
dat_train <- read.csv("~/santander2/train.csv", stringsAsFactors = FALSE)
dat_test <- read.csv("~/santander2/test.csv", stringsAsFactors = FALSE)

dat_test$TARGET <- NA
all_dat <- rbind(dat_train, dat_test)

for (i in names(all_dat)[-1])
{
	if (is.integer(all_dat[, i]) & length(unique(all_dat[, i])) == 1) 
	{
			all_dat[, i] <- NULL
			cat("Deleted constant variable: ", i, "\n")
		 
	}
}
```

#Duplicate columns

```{r}
temp <- names(all_dat)[duplicated(lapply(all_dat, summary))]
cat(temp, sep="\n")
all_dat <- all_dat[!duplicated(lapply(all_dat, summary))]
```

#Correlated variables

```{r}
cor_v <- abs(cor(all_dat))
diag(cor_v) <- 0
cor_v[upper.tri(cor_v)] <- 0
cor_v <- as.data.frame(which(cor_v > 0.85, arr.ind = T))
cat(names(all_dat)[unique(cor_v$row)], sep="\n")
all_dat <- all_dat[,-unique(cor_v$row)]
```

#Importance

```
xgbmodel <- xgboost(data=dtrain, nrounds=500, max.depth=5, eta=0.01, maximize=T, params=param)
Dimnames <- names(select(train, -ID, -TARGET))
importance_matrix <- xgb.importance(Dimnames,model= xgbmodel)
xgb.plot.importance(importance_matrix)
```

#Variables with missing values

```{r}
summary(all_dat$var3)
summary(all_dat[,grep('delta', names(all_dat))])
```

#Variables included in the model

```{r}
names(all_dat)
```

#Tuning

Stepsize (eta) = 0.01 seems to be the best.

max.depth = 5 seems to be the best.

#Variables Recognition
AGE = var15

#New
var42 num
num_ are ranges??

var17 financing product?